### PR TITLE
introduce a feature flags to control the frequency of checks

### PR DESCRIPTION
**Pull request by myaser**
#55

### CODE REVIEW

**Comment by zbindenren** [comment]
Thx for your contribution.

**Comment by myaser** [comment]
Would you please issue a release with these changes?

**Comment by zbindenren** [comment]
Currently a lot to do @ work. Try to update the helm chart and creating a new release next week.

**Comment by zbindenren** [comment]
A new docker image is releases: https://hub.docker.com/r/postfinance/kubenurse/tags

**Pull request merged**
